import React, { useState } from 'react'
import { jsPDF } from 'jspdf'

export default function ReportGenerator({
  patient,
  medications,
  interactions,
  riskScore,
  riskLevel,
  explanationSummary,
  onGenerate,
}) {
  const [previewVisible, setPreviewVisible] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)

  const handleGenerate = async () => {
    setIsGenerating(true)
    await onGenerate?.()
    setPreviewVisible(true)
    setIsGenerating(false)
  }

  const downloadPDF = () => {
    const doc = new jsPDF()
    let y = 20
    const lineHeight = 7

    doc.setFontSize(18)
    doc.text('Patient Report - HealthyCare', 20, y)
    y += lineHeight
    doc.setFontSize(10)
    doc.text('Polypharmacy Risk Checker for Elderly Patients', 20, y)
    y += lineHeight * 2

    doc.setFontSize(12)
    doc.text('Patient Details', 20, y)
    y += lineHeight
    doc.setFontSize(10)
    doc.text(`Name: ${patient?.name || 'N/A'}`, 20, y)
    y += lineHeight
    doc.text(`Age: ${patient?.age || 'N/A'} | Gender: ${patient?.gender || 'N/A'}`, 20, y)
    y += lineHeight
    doc.text(`Patient ID: ${patient?.patientId || 'N/A'}`, 20, y)
    y += lineHeight
    doc.text(`Conditions: ${patient?.conditions || 'None listed'}`, 20, y)
    y += lineHeight * 2

    doc.setFontSize(12)
    doc.text('Medication List', 20, y)
    y += lineHeight
    doc.setFontSize(10)
    ;(medications || []).forEach((m) => {
      doc.text(`• ${m}`, 20, y)
      y += lineHeight
    })
    y += lineHeight

    doc.setFontSize(12)
    doc.text('Detected Interactions', 20, y)
    y += lineHeight
    doc.setFontSize(10)
    if (interactions?.length) {
      interactions.forEach((i) => {
        doc.text(`${i.drugA} + ${i.drugB}: ${i.warning}`, 20, y)
        y += lineHeight
      })
    } else {
      doc.text('None detected', 20, y)
      y += lineHeight
    }
    y += lineHeight

    doc.setFontSize(12)
    doc.text(`Risk Score: ${riskScore ?? 0} (${riskLevel || 'N/A'})`, 20, y)
    y += lineHeight * 2

    doc.setFontSize(12)
    doc.text('AI Explanation Summary', 20, y)
    y += lineHeight
    doc.setFontSize(10)
    const summary = explanationSummary || 'No explanation generated yet.'
    doc.text(doc.splitTextToSize(summary, 170), 20, y)
    y += lineHeight * 3

    doc.setFontSize(8)
    doc.text('Generated by HealthyCare - Polypharmacy Risk Checker. For clinical support only. Always verify with a pharmacist.', 20, doc.internal.pageSize.height - 10)
    doc.save('healthycare-patient-report.pdf')
  }

  return (
    <div className="card p-5">
      <div className="card-header-accent">
        <span
          className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0"
          style={{ backgroundColor: 'rgba(71, 186, 135, 0.15)' }}
        >
          <svg className="w-5 h-5 text-brand-teal" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
        </span>
        <div className="min-w-0">
          <p className="section-label">Export</p>
          <h2 className="text-base font-bold text-slate-800 tracking-tight">Report Generator</h2>
        </div>
      </div>
      <button
        type="button"
        onClick={handleGenerate}
        disabled={isGenerating}
        className="btn-primary w-full mb-4 flex items-center justify-center gap-2 min-h-[48px]"
      >
        {isGenerating ? (
          <>
            <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
            Generating…
          </>
        ) : (
          'Generate Patient Report'
        )}
      </button>
      {previewVisible && (
        <div className="rounded-xl border border-slate-100 bg-slate-50/50 p-4 space-y-3 text-clinical">
          <p className="font-bold text-slate-700 text-[13px]">Preview</p>
          <ul className="text-slate-600 space-y-1">
            <li>• Patient: {patient?.name || 'N/A'} (Age: {patient?.age || 'N/A'})</li>
            <li>• Medications: {medications?.length ?? 0}</li>
            <li>• Interactions: {interactions?.length ?? 0} detected</li>
            <li>• Risk: {riskScore ?? 0} ({riskLevel || 'N/A'})</li>
          </ul>
          <button
            type="button"
            onClick={downloadPDF}
            className="btn-secondary w-full flex items-center justify-center gap-2 min-h-[48px]"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Download PDF
          </button>
        </div>
      )}
    </div>
  )
}
